package com.dsc.android.bootcamp1;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class RecyclerViewActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    private RecyclerViewAdapter recyclerViewAdapter;
    private List<RecyclerViewData> userList = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recycler_view);
        recyclerView = findViewById(R.id.recyclerView);
//        createMockList();
        apicall();
        setUpRecyclerView(); // call function
    }

    private void    apicall(){
        ApiServices apiServices = AppClient.getInstance().createService(ApiServices.class);
        retrofit2.Call<UserWrapper> call = apiServices.getUserList();

        //below code autogenerated! new & Capital C
        call.enqueue(new Callback<UserWrapper>() {
            @Override
            public void onResponse(Call<UserWrapper> call, Response<UserWrapper> response) {
                if (response.isSuccessful()){
                    if (response.body() != null){
                        userList.addAll(response.body().getRecyclerViewData());
                    }
                }
            }

            @Override
            public void onFailure(Call<UserWrapper> call, Throwable t) {

            }
        });
    }


//    coz constructor deleted from RecyclerviewData
//      private void createMockList(){
//        RecyclerViewData data; //object created
//        data = new RecyclerViewData("https://bit.ly/2NT7svr","Pratik Kumar Bathwal","887-1000-950");
//        userList.add(data);
//        data = new RecyclerViewData("https://bit.ly/2NT7svr","Pratik","111111111");
//        userList.add(data);
//        data = new RecyclerViewData("https://bit.ly/2NT7svr","Pratik Bathwal","22222222");
//        userList.add(data);
//        data = new RecyclerViewData("https://bit.ly/2NT7svr","Pro","333333333");
//        userList.add(data);
//        data = new RecyclerViewData("https://bit.ly/2NT7svr","PKB","44444444444");
//        userList.add(data);
//    }

    private void setUpRecyclerView(){
        recyclerViewAdapter = new RecyclerViewAdapter(this);//object
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(recyclerViewAdapter);
        recyclerViewAdapter.setRecyclerViewDataList(userList);
        recyclerViewAdapter.notifyDataSetChanged();
    }
}
